### ISSUE TITLE
Non-linear regression

### ISSUE THREAD

**Issue by statzhero** [elbersb/shapley#1]
Interesting package! Is it inspired by [reg**o**](http://www.marco-sunder.de/stata/rego.html)?

As I'm not too familiar with it: can one provide a pseudo-R<sup>2</sup> from a non-linear model to the `shapley` function and expect a useful result?

**Comment by elbersb** [comment]
The package is just a generic application of the Shapley algorithm (very much WIP, I should say). You can do R^2 decomposition (like rego) with it fairly easily, although you have to code up the value function yourself. And yes, you could do the same for a non-linear model.

**Comment by statzhero** [comment]
I did so, thank you!

**Comment by elbersb** [comment]
That's cool! Glad you found it useful.
